// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEKSGShR3Cj7HSGZ-Y5ZOt-z5wgzpMmDQ',
    appId: '1:628746497539:web:fc2ee79d4a7d30ed722836',
    messagingSenderId: '628746497539',
    projectId: 'waterriderdemo',
    authDomain: 'waterriderdemo.firebaseapp.com',
    storageBucket: 'waterriderdemo.appspot.com',
    measurementId: 'G-S543EFELDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_a-7Nm9VKeyHApwXm3dbT58utUNxH9I',
    appId: '1:628746497539:android:2704041cc9401a16722836',
    messagingSenderId: '628746497539',
    projectId: 'waterriderdemo',
    storageBucket: 'waterriderdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQw531ndI2FKKgk2-qBOVgz14jDeTQIcY',
    appId: '1:628746497539:ios:5378884c74f90112722836',
    messagingSenderId: '628746497539',
    projectId: 'waterriderdemo',
    storageBucket: 'waterriderdemo.appspot.com',
    iosBundleId: 'com.example.waterriderdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQw531ndI2FKKgk2-qBOVgz14jDeTQIcY',
    appId: '1:628746497539:ios:5378884c74f90112722836',
    messagingSenderId: '628746497539',
    projectId: 'waterriderdemo',
    storageBucket: 'waterriderdemo.appspot.com',
    iosBundleId: 'com.example.waterriderdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEKSGShR3Cj7HSGZ-Y5ZOt-z5wgzpMmDQ',
    appId: '1:628746497539:web:5ba7e9e08c31a575722836',
    messagingSenderId: '628746497539',
    projectId: 'waterriderdemo',
    authDomain: 'waterriderdemo.firebaseapp.com',
    storageBucket: 'waterriderdemo.appspot.com',
    measurementId: 'G-08P9RF50PF',
  );

}